### ISSUE TITLE
Support JwtParser configured via Bootique

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jjwt#1]
Support a minimal set of options to configure `JwtParser` object:

```yaml

// TODO: bootique-keystore
keystores:
   ks1:
      location: "classpath:abc.jks"
      password: "changeit"

jjwt:
   parser:
      requireIssuer: 'https://example.org'
      keyStore: ks1
      keyAlias: mykey
```
